### ISSUE TITLE
Make it more clear how to exit shop

### ISSUE THREAD

**Issue by arnesven** [arnesven/FatefulEight2#3]

**Comment by Ponha** [comment]
![bild](https://github.com/arnesven/FatefulEight2/assets/14105233/b2f619ca-24d2-4933-90d4-08ba1788fba1)

I do not know if this fix has made it in to the 1.25 release, but my experience is that the game soft locks when encountering a store. In the image I encountered a sorcerer, once I had bought the only item he had to sell I was unable to continue the game. I looked in all menus I could find to no avail.

**Comment by arnesven** [comment]
Should be fixed by shop redesign in 1.26, but I will have a look at sorcerer event and/or buying last item in shop.
